/**
 * Static template definitions for the template gallery.
 * Each template contains pre-configured fields that get loaded into the form builder.
 */

export interface FormTemplate {
  id: string
  title: string
  description: string
  category: TemplateCategory
  icon: string
  fieldCount: number
  fields: TemplateField[]
}

export type TemplateCategory =
  | 'Feedback'
  | 'Registration'
  | 'Survey'
  | 'Contact'
  | 'Application'

export const TEMPLATE_CATEGORIES: {
  name: TemplateCategory
  label: string
  description: string
}[] = [
  { name: 'Feedback', label: 'Feedback', description: 'Collect opinions and reviews' },
  { name: 'Registration', label: 'Registration', description: 'Sign-ups and enrollments' },
  { name: 'Survey', label: 'Survey', description: 'Research and satisfaction surveys' },
  { name: 'Contact', label: 'Contact', description: 'Contact and support forms' },
  { name: 'Application', label: 'Application', description: 'Job and volunteer applications' },
]

// Using a loose type here so templates can reference any field type without importing all configs
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type TemplateField = Record<string, any>

let _counter = 0
function uid(prefix: string) {
  _counter++
  return `${prefix}_tpl_${_counter}`
}

// ────────────────────────────────────────────────────────────
// TEMPLATES
// ────────────────────────────────────────────────────────────

export const TEMPLATES: FormTemplate[] = [
  // ── FEEDBACK ──────────────────────────────────────────────
  {
    id: 'customer-feedback',
    title: 'Customer Feedback',
    description: 'Gather valuable feedback from your customers about their experience with your product or service.',
    category: 'Feedback',
    icon: '💬',
    fieldCount: 6,
    fields: [
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Full Name',
        placeholder: 'e.g., Jane Smith',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Email Address',
        placeholder: 'you@example.com',
        description: 'We\'ll use this to follow up on your feedback.',
        required: true,
        disabled: false,
        inputType: 'email',
      },
      {
        id: uid('select'),
        uniqueIdentifier: 'single-select',
        label: 'How did you hear about us?',
        placeholder: 'Select one...',
        description: '',
        required: false,
        disabled: false,
        options: [
          { label: 'Search Engine', value: 'search_engine' },
          { label: 'Social Media', value: 'social_media' },
          { label: 'Friend or Colleague', value: 'referral' },
          { label: 'Advertisement', value: 'ad' },
          { label: 'Other', value: 'other' },
        ],
      },
      {
        id: uid('slider'),
        uniqueIdentifier: 'slider',
        label: 'Overall Satisfaction',
        description: 'Rate your experience from 1 (poor) to 10 (excellent).',
        required: true,
        disabled: false,
        min: 1,
        max: 10,
        step: 1,
        showValue: true,
        defaultValue: 7,
      },
      {
        id: uid('radio'),
        uniqueIdentifier: 'radio-group',
        label: 'Would you recommend us to a friend?',
        description: '',
        required: true,
        disabled: false,
        orientation: 'horizontal',
        options: [
          { label: 'Definitely', value: 'definitely' },
          { label: 'Probably', value: 'probably' },
          { label: 'Not sure', value: 'not_sure' },
          { label: 'Probably not', value: 'probably_not' },
        ],
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'Additional Comments',
        placeholder: 'Tell us more about your experience...',
        description: 'Any other thoughts or suggestions?',
        required: false,
        disabled: false,
      },
    ],
  },
  {
    id: 'product-review',
    title: 'Product Review',
    description: 'Collect detailed product reviews with ratings to improve your offerings.',
    category: 'Feedback',
    icon: '⭐',
    fieldCount: 7,
    fields: [
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Your Name',
        placeholder: 'e.g., Alex Johnson',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Product Name',
        placeholder: 'Which product are you reviewing?',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('slider'),
        uniqueIdentifier: 'slider',
        label: 'Quality Rating',
        description: 'Rate the product quality from 1 to 5.',
        required: true,
        disabled: false,
        min: 1,
        max: 5,
        step: 1,
        showValue: true,
        defaultValue: 4,
      },
      {
        id: uid('slider'),
        uniqueIdentifier: 'slider',
        label: 'Value for Money',
        description: 'Rate the value for money from 1 to 5.',
        required: true,
        disabled: false,
        min: 1,
        max: 5,
        step: 1,
        showValue: true,
        defaultValue: 3,
      },
      {
        id: uid('radio'),
        uniqueIdentifier: 'radio-group',
        label: 'Would you buy this product again?',
        description: '',
        required: true,
        disabled: false,
        orientation: 'horizontal',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'Maybe', value: 'maybe' },
          { label: 'No', value: 'no' },
        ],
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'What did you like most?',
        placeholder: 'Share what stood out to you...',
        description: '',
        required: false,
        disabled: false,
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'What could be improved?',
        placeholder: 'Any suggestions for improvement...',
        description: '',
        required: false,
        disabled: false,
      },
    ],
  },
  {
    id: 'bug-report',
    title: 'Bug Report',
    description: 'Let users report bugs and issues with detailed reproduction steps.',
    category: 'Feedback',
    icon: '🐛',
    fieldCount: 7,
    fields: [
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Reporter Name',
        placeholder: 'Your name',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Reporter Email',
        placeholder: 'you@company.com',
        description: '',
        required: true,
        disabled: false,
        inputType: 'email',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Bug Title',
        placeholder: 'Brief summary of the issue',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('select'),
        uniqueIdentifier: 'single-select',
        label: 'Severity',
        placeholder: 'How severe is this bug?',
        description: '',
        required: true,
        disabled: false,
        options: [
          { label: 'Critical — App is unusable', value: 'critical' },
          { label: 'High — Major feature broken', value: 'high' },
          { label: 'Medium — Feature partially broken', value: 'medium' },
          { label: 'Low — Minor issue', value: 'low' },
        ],
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'Steps to Reproduce',
        placeholder: '1. Go to...\n2. Click on...\n3. Observe...',
        description: 'Please provide detailed steps so we can reproduce the issue.',
        required: true,
        disabled: false,
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'Expected Behavior',
        placeholder: 'What should have happened?',
        description: '',
        required: true,
        disabled: false,
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'Actual Behavior',
        placeholder: 'What actually happened?',
        description: '',
        required: true,
        disabled: false,
      },
    ],
  },

  // ── REGISTRATION ──────────────────────────────────────────
  {
    id: 'event-registration',
    title: 'Event Registration',
    description: 'Manage event sign-ups with attendee details, meal preferences, and session choices.',
    category: 'Registration',
    icon: '🎫',
    fieldCount: 7,
    fields: [
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Full Name',
        placeholder: 'e.g., Sarah Connor',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Email Address',
        placeholder: 'you@example.com',
        description: 'We\'ll send your confirmation here.',
        required: true,
        disabled: false,
        inputType: 'email',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Phone Number',
        placeholder: '+1 (555) 000-0000',
        description: '',
        required: false,
        disabled: false,
        inputType: 'tel',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Organization / Company',
        placeholder: 'Your company name',
        description: '',
        required: false,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('select'),
        uniqueIdentifier: 'single-select',
        label: 'Dietary Preference',
        placeholder: 'Select your preference',
        description: '',
        required: false,
        disabled: false,
        options: [
          { label: 'No restrictions', value: 'none' },
          { label: 'Vegetarian', value: 'vegetarian' },
          { label: 'Vegan', value: 'vegan' },
          { label: 'Gluten-free', value: 'gluten_free' },
          { label: 'Halal', value: 'halal' },
          { label: 'Kosher', value: 'kosher' },
        ],
      },
      {
        id: uid('multi'),
        uniqueIdentifier: 'multi-select',
        label: 'Which sessions will you attend?',
        placeholder: 'Select sessions',
        description: 'You can select multiple sessions.',
        required: true,
        disabled: false,
        options: [
          { label: 'Opening Keynote', value: 'keynote' },
          { label: 'Workshop A — Design', value: 'workshop_a' },
          { label: 'Workshop B — Engineering', value: 'workshop_b' },
          { label: 'Panel Discussion', value: 'panel' },
          { label: 'Networking Lunch', value: 'lunch' },
          { label: 'Closing Ceremony', value: 'closing' },
        ],
        searchable: false,
        allowCustomValues: false,
      },
      {
        id: uid('checkbox'),
        uniqueIdentifier: 'checkbox',
        label: 'I agree to the event terms and conditions',
        placeholder: '',
        description: '',
        required: true,
        disabled: false,
      },
    ],
  },
  {
    id: 'newsletter-signup',
    title: 'Newsletter Signup',
    description: 'Build your mailing list with a clean, simple signup form.',
    category: 'Registration',
    icon: '📧',
    fieldCount: 4,
    fields: [
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'First Name',
        placeholder: 'Your first name',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Email Address',
        placeholder: 'you@example.com',
        description: '',
        required: true,
        disabled: false,
        inputType: 'email',
      },
      {
        id: uid('multi'),
        uniqueIdentifier: 'multi-select',
        label: 'Topics of Interest',
        placeholder: 'What do you want to hear about?',
        description: '',
        required: false,
        disabled: false,
        options: [
          { label: 'Product Updates', value: 'product' },
          { label: 'Industry News', value: 'news' },
          { label: 'Tips & Tutorials', value: 'tutorials' },
          { label: 'Company Announcements', value: 'announcements' },
          { label: 'Events & Webinars', value: 'events' },
        ],
        searchable: false,
        allowCustomValues: false,
      },
      {
        id: uid('checkbox'),
        uniqueIdentifier: 'checkbox',
        label: 'I agree to receive marketing emails',
        placeholder: '',
        description: 'You can unsubscribe at any time.',
        required: true,
        disabled: false,
      },
    ],
  },
  {
    id: 'workshop-registration',
    title: 'Workshop Registration',
    description: 'Register participants for workshops with skill level assessment and scheduling.',
    category: 'Registration',
    icon: '🎓',
    fieldCount: 7,
    fields: [
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Full Name',
        placeholder: 'e.g., Michael Chen',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Email',
        placeholder: 'you@example.com',
        description: '',
        required: true,
        disabled: false,
        inputType: 'email',
      },
      {
        id: uid('radio'),
        uniqueIdentifier: 'radio-group',
        label: 'Experience Level',
        description: 'This helps us tailor the workshop content.',
        required: true,
        disabled: false,
        orientation: 'vertical',
        options: [
          { label: 'Beginner — Just getting started', value: 'beginner' },
          { label: 'Intermediate — Some experience', value: 'intermediate' },
          { label: 'Advanced — Very experienced', value: 'advanced' },
        ],
      },
      {
        id: uid('select'),
        uniqueIdentifier: 'single-select',
        label: 'Preferred Session',
        placeholder: 'Choose a time slot',
        description: '',
        required: true,
        disabled: false,
        options: [
          { label: 'Morning (9:00 AM - 12:00 PM)', value: 'morning' },
          { label: 'Afternoon (1:00 PM - 4:00 PM)', value: 'afternoon' },
          { label: 'Evening (6:00 PM - 9:00 PM)', value: 'evening' },
        ],
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'What do you hope to learn?',
        placeholder: 'Share your learning goals...',
        description: '',
        required: false,
        disabled: false,
      },
      {
        id: uid('select'),
        uniqueIdentifier: 'single-select',
        label: 'How did you find this workshop?',
        placeholder: 'Select one...',
        description: '',
        required: false,
        disabled: false,
        options: [
          { label: 'Website', value: 'website' },
          { label: 'Social Media', value: 'social' },
          { label: 'Email', value: 'email' },
          { label: 'Word of Mouth', value: 'word_of_mouth' },
          { label: 'Other', value: 'other' },
        ],
      },
      {
        id: uid('checkbox'),
        uniqueIdentifier: 'checkbox',
        label: 'I agree to the workshop policies',
        placeholder: '',
        description: '',
        required: true,
        disabled: false,
      },
    ],
  },

  // ── SURVEY ────────────────────────────────────────────────
  {
    id: 'employee-satisfaction',
    title: 'Employee Satisfaction',
    description: 'Measure workplace satisfaction and gather anonymous feedback from your team.',
    category: 'Survey',
    icon: '📊',
    fieldCount: 8,
    fields: [
      {
        id: uid('select'),
        uniqueIdentifier: 'single-select',
        label: 'Department',
        placeholder: 'Select your department',
        description: '',
        required: true,
        disabled: false,
        options: [
          { label: 'Engineering', value: 'engineering' },
          { label: 'Design', value: 'design' },
          { label: 'Marketing', value: 'marketing' },
          { label: 'Sales', value: 'sales' },
          { label: 'Operations', value: 'operations' },
          { label: 'Human Resources', value: 'hr' },
          { label: 'Finance', value: 'finance' },
          { label: 'Other', value: 'other' },
        ],
      },
      {
        id: uid('slider'),
        uniqueIdentifier: 'slider',
        label: 'Overall Job Satisfaction',
        description: '1 = Very Dissatisfied, 10 = Very Satisfied',
        required: true,
        disabled: false,
        min: 1,
        max: 10,
        step: 1,
        showValue: true,
        defaultValue: 7,
      },
      {
        id: uid('slider'),
        uniqueIdentifier: 'slider',
        label: 'Work-Life Balance',
        description: '1 = Very Poor, 10 = Excellent',
        required: true,
        disabled: false,
        min: 1,
        max: 10,
        step: 1,
        showValue: true,
        defaultValue: 6,
      },
      {
        id: uid('slider'),
        uniqueIdentifier: 'slider',
        label: 'Team Collaboration',
        description: '1 = Very Poor, 10 = Excellent',
        required: true,
        disabled: false,
        min: 1,
        max: 10,
        step: 1,
        showValue: true,
        defaultValue: 7,
      },
      {
        id: uid('radio'),
        uniqueIdentifier: 'radio-group',
        label: 'I feel valued at this company',
        description: '',
        required: true,
        disabled: false,
        orientation: 'horizontal',
        options: [
          { label: 'Strongly Agree', value: 'strongly_agree' },
          { label: 'Agree', value: 'agree' },
          { label: 'Neutral', value: 'neutral' },
          { label: 'Disagree', value: 'disagree' },
          { label: 'Strongly Disagree', value: 'strongly_disagree' },
        ],
      },
      {
        id: uid('radio'),
        uniqueIdentifier: 'radio-group',
        label: 'I would recommend this company as a great place to work',
        description: '',
        required: true,
        disabled: false,
        orientation: 'horizontal',
        options: [
          { label: 'Strongly Agree', value: 'strongly_agree' },
          { label: 'Agree', value: 'agree' },
          { label: 'Neutral', value: 'neutral' },
          { label: 'Disagree', value: 'disagree' },
          { label: 'Strongly Disagree', value: 'strongly_disagree' },
        ],
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'What do you enjoy most about working here?',
        placeholder: 'Share what makes your work experience positive...',
        description: '',
        required: false,
        disabled: false,
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'What improvements would you suggest?',
        placeholder: 'Your suggestions for making this a better workplace...',
        description: 'All feedback is anonymous and confidential.',
        required: false,
        disabled: false,
      },
    ],
  },
  {
    id: 'market-research',
    title: 'Market Research',
    description: 'Understand your target audience with demographic and preference data collection.',
    category: 'Survey',
    icon: '🔍',
    fieldCount: 7,
    fields: [
      {
        id: uid('select'),
        uniqueIdentifier: 'single-select',
        label: 'Age Range',
        placeholder: 'Select your age range',
        description: '',
        required: true,
        disabled: false,
        options: [
          { label: '18-24', value: '18_24' },
          { label: '25-34', value: '25_34' },
          { label: '35-44', value: '35_44' },
          { label: '45-54', value: '45_54' },
          { label: '55-64', value: '55_64' },
          { label: '65+', value: '65_plus' },
        ],
      },
      {
        id: uid('select'),
        uniqueIdentifier: 'single-select',
        label: 'Industry',
        placeholder: 'Select your industry',
        description: '',
        required: true,
        disabled: false,
        options: [
          { label: 'Technology', value: 'tech' },
          { label: 'Healthcare', value: 'healthcare' },
          { label: 'Education', value: 'education' },
          { label: 'Finance', value: 'finance' },
          { label: 'Retail', value: 'retail' },
          { label: 'Manufacturing', value: 'manufacturing' },
          { label: 'Other', value: 'other' },
        ],
      },
      {
        id: uid('radio'),
        uniqueIdentifier: 'radio-group',
        label: 'How often do you use products in this category?',
        description: '',
        required: true,
        disabled: false,
        orientation: 'vertical',
        options: [
          { label: 'Daily', value: 'daily' },
          { label: 'Weekly', value: 'weekly' },
          { label: 'Monthly', value: 'monthly' },
          { label: 'Rarely', value: 'rarely' },
          { label: 'Never', value: 'never' },
        ],
      },
      {
        id: uid('multi'),
        uniqueIdentifier: 'multi-select',
        label: 'What factors influence your purchasing decisions?',
        placeholder: 'Select all that apply',
        description: '',
        required: true,
        disabled: false,
        options: [
          { label: 'Price', value: 'price' },
          { label: 'Quality', value: 'quality' },
          { label: 'Brand Reputation', value: 'brand' },
          { label: 'Reviews', value: 'reviews' },
          { label: 'Recommendations', value: 'recommendations' },
          { label: 'Features', value: 'features' },
          { label: 'Customer Support', value: 'support' },
        ],
        searchable: false,
        allowCustomValues: false,
      },
      {
        id: uid('slider'),
        uniqueIdentifier: 'slider',
        label: 'Monthly budget for this category',
        description: 'Approximate monthly spend in dollars.',
        required: false,
        disabled: false,
        min: 0,
        max: 500,
        step: 25,
        showValue: true,
        defaultValue: 100,
      },
      {
        id: uid('radio'),
        uniqueIdentifier: 'radio-group',
        label: 'How satisfied are you with current market options?',
        description: '',
        required: true,
        disabled: false,
        orientation: 'horizontal',
        options: [
          { label: 'Very Satisfied', value: 'very_satisfied' },
          { label: 'Satisfied', value: 'satisfied' },
          { label: 'Neutral', value: 'neutral' },
          { label: 'Dissatisfied', value: 'dissatisfied' },
        ],
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'What features would your ideal product have?',
        placeholder: 'Describe your dream product...',
        description: '',
        required: false,
        disabled: false,
      },
    ],
  },
  {
    id: 'course-evaluation',
    title: 'Course Evaluation',
    description: 'Collect student feedback on courses, instructors, and learning materials.',
    category: 'Survey',
    icon: '📝',
    fieldCount: 7,
    fields: [
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Course Name',
        placeholder: 'e.g., Introduction to Machine Learning',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Instructor Name',
        placeholder: 'Name of the instructor',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('slider'),
        uniqueIdentifier: 'slider',
        label: 'Course Content Quality',
        description: '1 = Poor, 5 = Excellent',
        required: true,
        disabled: false,
        min: 1,
        max: 5,
        step: 1,
        showValue: true,
        defaultValue: 4,
      },
      {
        id: uid('slider'),
        uniqueIdentifier: 'slider',
        label: 'Instructor Effectiveness',
        description: '1 = Poor, 5 = Excellent',
        required: true,
        disabled: false,
        min: 1,
        max: 5,
        step: 1,
        showValue: true,
        defaultValue: 4,
      },
      {
        id: uid('slider'),
        uniqueIdentifier: 'slider',
        label: 'Course Materials & Resources',
        description: '1 = Poor, 5 = Excellent',
        required: true,
        disabled: false,
        min: 1,
        max: 5,
        step: 1,
        showValue: true,
        defaultValue: 3,
      },
      {
        id: uid('radio'),
        uniqueIdentifier: 'radio-group',
        label: 'Would you recommend this course?',
        description: '',
        required: true,
        disabled: false,
        orientation: 'horizontal',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'Maybe', value: 'maybe' },
          { label: 'No', value: 'no' },
        ],
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'Additional Feedback',
        placeholder: 'Any other comments about the course...',
        description: '',
        required: false,
        disabled: false,
      },
    ],
  },

  // ── CONTACT ───────────────────────────────────────────────
  {
    id: 'contact-us',
    title: 'Contact Us',
    description: 'A simple, professional contact form for your website visitors.',
    category: 'Contact',
    icon: '📬',
    fieldCount: 5,
    fields: [
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Full Name',
        placeholder: 'e.g., John Doe',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Email Address',
        placeholder: 'you@example.com',
        description: '',
        required: true,
        disabled: false,
        inputType: 'email',
      },
      {
        id: uid('select'),
        uniqueIdentifier: 'single-select',
        label: 'Subject',
        placeholder: 'What is this about?',
        description: '',
        required: true,
        disabled: false,
        options: [
          { label: 'General Inquiry', value: 'general' },
          { label: 'Sales', value: 'sales' },
          { label: 'Support', value: 'support' },
          { label: 'Partnership', value: 'partnership' },
          { label: 'Press / Media', value: 'press' },
          { label: 'Other', value: 'other' },
        ],
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'Message',
        placeholder: 'How can we help you?',
        description: '',
        required: true,
        disabled: false,
      },
      {
        id: uid('checkbox'),
        uniqueIdentifier: 'checkbox',
        label: 'I agree to the privacy policy',
        placeholder: '',
        description: '',
        required: true,
        disabled: false,
      },
    ],
  },
  {
    id: 'support-request',
    title: 'Support Request',
    description: 'Help users submit detailed support tickets for faster resolution.',
    category: 'Contact',
    icon: '🛟',
    fieldCount: 7,
    fields: [
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Full Name',
        placeholder: 'Your name',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Email Address',
        placeholder: 'you@example.com',
        description: 'We\'ll send updates about your ticket here.',
        required: true,
        disabled: false,
        inputType: 'email',
      },
      {
        id: uid('select'),
        uniqueIdentifier: 'single-select',
        label: 'Issue Category',
        placeholder: 'Select category',
        description: '',
        required: true,
        disabled: false,
        options: [
          { label: 'Account & Billing', value: 'billing' },
          { label: 'Technical Issue', value: 'technical' },
          { label: 'Feature Request', value: 'feature' },
          { label: 'Data & Privacy', value: 'privacy' },
          { label: 'Other', value: 'other' },
        ],
      },
      {
        id: uid('select'),
        uniqueIdentifier: 'single-select',
        label: 'Priority',
        placeholder: 'How urgent is this?',
        description: '',
        required: true,
        disabled: false,
        options: [
          { label: 'Low — No rush', value: 'low' },
          { label: 'Medium — Needs attention soon', value: 'medium' },
          { label: 'High — Blocking my work', value: 'high' },
          { label: 'Critical — System down', value: 'critical' },
        ],
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Subject',
        placeholder: 'Brief description of the issue',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'Detailed Description',
        placeholder: 'Please describe the issue in detail...',
        description: 'Include any error messages, screenshots, or steps to reproduce.',
        required: true,
        disabled: false,
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Browser / Device',
        placeholder: 'e.g., Chrome on macOS',
        description: 'Helps us reproduce the issue.',
        required: false,
        disabled: false,
        inputType: 'text',
      },
    ],
  },

  // ── APPLICATION ───────────────────────────────────────────
  {
    id: 'job-application',
    title: 'Job Application',
    description: 'Streamline your hiring process with a comprehensive job application form.',
    category: 'Application',
    icon: '💼',
    fieldCount: 8,
    fields: [
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Full Name',
        placeholder: 'e.g., Jessica Williams',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Email Address',
        placeholder: 'you@example.com',
        description: '',
        required: true,
        disabled: false,
        inputType: 'email',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Phone Number',
        placeholder: '+1 (555) 000-0000',
        description: '',
        required: true,
        disabled: false,
        inputType: 'tel',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'LinkedIn Profile URL',
        placeholder: 'https://linkedin.com/in/yourprofile',
        description: '',
        required: false,
        disabled: false,
        inputType: 'url',
      },
      {
        id: uid('select'),
        uniqueIdentifier: 'single-select',
        label: 'Position Applied For',
        placeholder: 'Select position',
        description: '',
        required: true,
        disabled: false,
        options: [
          { label: 'Software Engineer', value: 'swe' },
          { label: 'Product Designer', value: 'designer' },
          { label: 'Product Manager', value: 'pm' },
          { label: 'Data Analyst', value: 'data_analyst' },
          { label: 'Marketing Specialist', value: 'marketing' },
          { label: 'Customer Success', value: 'cs' },
          { label: 'Other', value: 'other' },
        ],
      },
      {
        id: uid('number'),
        uniqueIdentifier: 'number-input',
        label: 'Years of Experience',
        placeholder: 'e.g., 5',
        description: '',
        required: true,
        disabled: false,
        allowDecimals: false,
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'Why do you want to join our team?',
        placeholder: 'Tell us about your motivation...',
        description: '',
        required: true,
        disabled: false,
      },
      {
        id: uid('radio'),
        uniqueIdentifier: 'radio-group',
        label: 'When can you start?',
        description: '',
        required: true,
        disabled: false,
        orientation: 'vertical',
        options: [
          { label: 'Immediately', value: 'immediately' },
          { label: 'Within 2 weeks', value: '2_weeks' },
          { label: 'Within 1 month', value: '1_month' },
          { label: 'Within 3 months', value: '3_months' },
        ],
      },
    ],
  },
  {
    id: 'volunteer-application',
    title: 'Volunteer Application',
    description: 'Recruit and screen volunteers with availability and skills assessment.',
    category: 'Application',
    icon: '🤝',
    fieldCount: 7,
    fields: [
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Full Name',
        placeholder: 'Your full name',
        description: '',
        required: true,
        disabled: false,
        inputType: 'text',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Email Address',
        placeholder: 'you@example.com',
        description: '',
        required: true,
        disabled: false,
        inputType: 'email',
      },
      {
        id: uid('text'),
        uniqueIdentifier: 'text-input',
        label: 'Phone Number',
        placeholder: '+1 (555) 000-0000',
        description: '',
        required: false,
        disabled: false,
        inputType: 'tel',
      },
      {
        id: uid('multi'),
        uniqueIdentifier: 'multi-select',
        label: 'Areas of Interest',
        placeholder: 'Select areas you\'d like to help with',
        description: '',
        required: true,
        disabled: false,
        options: [
          { label: 'Event Planning', value: 'events' },
          { label: 'Fundraising', value: 'fundraising' },
          { label: 'Marketing & Communications', value: 'marketing' },
          { label: 'Teaching & Mentoring', value: 'teaching' },
          { label: 'Community Outreach', value: 'outreach' },
          { label: 'Administrative Support', value: 'admin' },
          { label: 'Technical / IT Support', value: 'tech' },
        ],
        searchable: false,
        allowCustomValues: false,
      },
      {
        id: uid('multi'),
        uniqueIdentifier: 'multi-select',
        label: 'Availability',
        placeholder: 'When are you available?',
        description: '',
        required: true,
        disabled: false,
        options: [
          { label: 'Weekday Mornings', value: 'weekday_morning' },
          { label: 'Weekday Afternoons', value: 'weekday_afternoon' },
          { label: 'Weekday Evenings', value: 'weekday_evening' },
          { label: 'Weekends', value: 'weekends' },
        ],
        searchable: false,
        allowCustomValues: false,
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'Relevant Experience',
        placeholder: 'Tell us about any relevant volunteer or work experience...',
        description: '',
        required: false,
        disabled: false,
      },
      {
        id: uid('textarea'),
        uniqueIdentifier: 'text-area',
        label: 'Why do you want to volunteer?',
        placeholder: 'Share your motivation...',
        description: '',
        required: true,
        disabled: false,
      },
    ],
  },
]

/**
 * Get a template by its ID
 */
export function getTemplateById(id: string): FormTemplate | undefined {
  return TEMPLATES.find((t) => t.id === id)
}

/**
 * Get templates filtered by category
 */
export function getTemplatesByCategory(category: TemplateCategory): FormTemplate[] {
  return TEMPLATES.filter((t) => t.category === category)
}
