/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ApiFormsRouteImport } from './routes/api/forms'
import { Route as ApiGeneratewithaiRouteRouteImport } from './routes/api/generatewithai/route'
import { Route as ApiHealthcheckRouteImport } from './routes/api/healthcheck'
import { Route as ApiTemplatesRouteImport } from './routes/api/templates'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as ApiAnalyticsOverviewRouteImport } from './routes/api/analytics/overview'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFormsIdRouteImport } from './routes/api/forms/$id'
import { Route as ApiFormsImportGoogleFormRouteImport } from './routes/api/forms/import-google-form'
import { Route as ApiFormsNewRouteImport } from './routes/api/forms/new'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as DashboardFormsIndexRouteImport } from './routes/dashboard/forms/index'
import { Route as DashboardTemplatesIndexRouteImport } from './routes/dashboard/templates/index'
import { Route as FormsSlugIndexRouteImport } from './routes/forms/$slug/index'
import { Route as ApiAnalyticsFormsIdRouteImport } from './routes/api/analytics/forms/$id'
import { Route as ApiFormsIdDeleteRouteImport } from './routes/api/forms/$id/delete'
import { Route as ApiFormsIdDuplicateRouteImport } from './routes/api/forms/$id/duplicate'
import { Route as ApiFormsIdResponsesRouteImport } from './routes/api/forms/$id/responses'
import { Route as ApiFormsIdSubmitRouteImport } from './routes/api/forms/$id/submit'
import { Route as ApiFormsIdUpdateRouteImport } from './routes/api/forms/$id/update'
import { Route as ApiFormsIdUploadsRouteImport } from './routes/api/forms/$id/uploads'
import { Route as ApiFormsIdViewFormRouteImport } from './routes/api/forms/$id/viewForm'
import { Route as ApiFormsImportGoogleFormConnectRouteImport } from './routes/api/forms/import-google-form/connect'
import { Route as ApiIntegrationsFileUploadsCallbackRouteImport } from './routes/api/integrations/file-uploads/callback'
import { Route as ApiIntegrationsGoogleFormsImportCallbackRouteImport } from './routes/api/integrations/google-forms-import/callback'
import { Route as ApiIntegrationsGoogleSheetsCallbackRouteImport } from './routes/api/integrations/google-sheets/callback'
import { Route as ApiInternalGoogleSheetsSyncRouteImport } from './routes/api/internal/google-sheets/sync'
import { Route as DashboardBuilderSlugIndexRouteImport } from './routes/dashboard/builder/$slug/index'
import { Route as DashboardFormsFormIdAnalyticsRouteImport } from './routes/dashboard/forms/$formId/analytics'
import { Route as DashboardFormsFormIdResponsesRouteImport } from './routes/dashboard/forms/$formId/responses'
import { Route as ApiAnalyticsFormsIdOverviewRouteImport } from './routes/api/analytics/forms/$id/overview'
import { Route as ApiAnalyticsFormsIdTodayRouteImport } from './routes/api/analytics/forms/$id/today'
import { Route as ApiAnalyticsFormsIdV2RouteImport } from './routes/api/analytics/forms/$id/v2'
import { Route as ApiFormsIdIntegrationsGoogleSheetsRouteImport } from './routes/api/forms/$id/integrations/google-sheets'
import { Route as ApiFormsIdUploadsUploadIdRouteImport } from './routes/api/forms/$id/uploads/$uploadId'
import { Route as ApiAnalyticsFormsIdV2DetailedRouteImport } from './routes/api/analytics/forms/$id/v2/detailed'
import { Route as ApiFormsIdIntegrationsGoogleSheetsConnectRouteImport } from './routes/api/forms/$id/integrations/google-sheets/connect'
import { Route as ApiFormsIdIntegrationsGoogleSheetsCreateRouteImport } from './routes/api/forms/$id/integrations/google-sheets/create'
import { Route as ApiFormsIdIntegrationsGoogleSheetsPickerTokenRouteImport } from './routes/api/forms/$id/integrations/google-sheets/picker-token'
import { Route as ApiFormsIdIntegrationsGoogleSheetsSelectionRouteImport } from './routes/api/forms/$id/integrations/google-sheets/selection'
import { Route as ApiFormsIdUploadsFieldsFieldIdConnectRouteImport } from './routes/api/forms/$id/uploads/fields/$fieldId/connect'
import { Route as ApiFormsIdUploadsFieldsFieldIdIntegrationRouteImport } from './routes/api/forms/$id/uploads/fields/$fieldId/integration'
import { Route as ApiFormsIdUploadsFieldsFieldIdPickerTokenRouteImport } from './routes/api/forms/$id/uploads/fields/$fieldId/picker-token'
import { Route as ApiFormsIdUploadsFieldsFieldIdSelectionRouteImport } from './routes/api/forms/$id/uploads/fields/$fieldId/selection'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsRoute = ApiFormsRouteImport.update({
  id: '/api/forms',
  path: '/api/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratewithaiRouteRoute = ApiGeneratewithaiRouteRouteImport.update({
  id: '/api/generatewithai',
  path: '/api/generatewithai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthcheckRoute = ApiHealthcheckRouteImport.update({
  id: '/api/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesRoute = ApiTemplatesRouteImport.update({
  id: '/api/templates',
  path: '/api/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsOverviewRoute = ApiAnalyticsOverviewRouteImport.update({
  id: '/api/analytics/overview',
  path: '/api/analytics/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsIdRoute = ApiFormsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFormsRoute,
} as any)
const ApiFormsImportGoogleFormRoute =
  ApiFormsImportGoogleFormRouteImport.update({
    id: '/import-google-form',
    path: '/import-google-form',
    getParentRoute: () => ApiFormsRoute,
  } as any)
const ApiFormsNewRoute = ApiFormsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ApiFormsRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFormsIndexRoute = DashboardFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTemplatesIndexRoute = DashboardTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const FormsSlugIndexRoute = FormsSlugIndexRouteImport.update({
  id: '/forms/$slug/',
  path: '/forms/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsFormsIdRoute = ApiAnalyticsFormsIdRouteImport.update({
  id: '/api/analytics/forms/$id',
  path: '/api/analytics/forms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsIdDeleteRoute = ApiFormsIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => ApiFormsIdRoute,
} as any)
const ApiFormsIdDuplicateRoute = ApiFormsIdDuplicateRouteImport.update({
  id: '/duplicate',
  path: '/duplicate',
  getParentRoute: () => ApiFormsIdRoute,
} as any)
const ApiFormsIdResponsesRoute = ApiFormsIdResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => ApiFormsIdRoute,
} as any)
const ApiFormsIdSubmitRoute = ApiFormsIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ApiFormsIdRoute,
} as any)
const ApiFormsIdUpdateRoute = ApiFormsIdUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => ApiFormsIdRoute,
} as any)
const ApiFormsIdUploadsRoute = ApiFormsIdUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => ApiFormsIdRoute,
} as any)
const ApiFormsIdViewFormRoute = ApiFormsIdViewFormRouteImport.update({
  id: '/viewForm',
  path: '/viewForm',
  getParentRoute: () => ApiFormsIdRoute,
} as any)
const ApiFormsImportGoogleFormConnectRoute =
  ApiFormsImportGoogleFormConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => ApiFormsImportGoogleFormRoute,
  } as any)
const ApiIntegrationsFileUploadsCallbackRoute =
  ApiIntegrationsFileUploadsCallbackRouteImport.update({
    id: '/api/integrations/file-uploads/callback',
    path: '/api/integrations/file-uploads/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleFormsImportCallbackRoute =
  ApiIntegrationsGoogleFormsImportCallbackRouteImport.update({
    id: '/api/integrations/google-forms-import/callback',
    path: '/api/integrations/google-forms-import/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsCallbackRoute =
  ApiIntegrationsGoogleSheetsCallbackRouteImport.update({
    id: '/api/integrations/google-sheets/callback',
    path: '/api/integrations/google-sheets/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalGoogleSheetsSyncRoute =
  ApiInternalGoogleSheetsSyncRouteImport.update({
    id: '/api/internal/google-sheets/sync',
    path: '/api/internal/google-sheets/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardBuilderSlugIndexRoute =
  DashboardBuilderSlugIndexRouteImport.update({
    id: '/builder/$slug/',
    path: '/builder/$slug/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardFormsFormIdAnalyticsRoute =
  DashboardFormsFormIdAnalyticsRouteImport.update({
    id: '/forms/$formId/analytics',
    path: '/forms/$formId/analytics',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardFormsFormIdResponsesRoute =
  DashboardFormsFormIdResponsesRouteImport.update({
    id: '/forms/$formId/responses',
    path: '/forms/$formId/responses',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiAnalyticsFormsIdOverviewRoute =
  ApiAnalyticsFormsIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ApiAnalyticsFormsIdRoute,
  } as any)
const ApiAnalyticsFormsIdTodayRoute =
  ApiAnalyticsFormsIdTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => ApiAnalyticsFormsIdRoute,
  } as any)
const ApiAnalyticsFormsIdV2Route = ApiAnalyticsFormsIdV2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => ApiAnalyticsFormsIdRoute,
} as any)
const ApiFormsIdIntegrationsGoogleSheetsRoute =
  ApiFormsIdIntegrationsGoogleSheetsRouteImport.update({
    id: '/integrations/google-sheets',
    path: '/integrations/google-sheets',
    getParentRoute: () => ApiFormsIdRoute,
  } as any)
const ApiFormsIdUploadsUploadIdRoute =
  ApiFormsIdUploadsUploadIdRouteImport.update({
    id: '/$uploadId',
    path: '/$uploadId',
    getParentRoute: () => ApiFormsIdUploadsRoute,
  } as any)
const ApiAnalyticsFormsIdV2DetailedRoute =
  ApiAnalyticsFormsIdV2DetailedRouteImport.update({
    id: '/detailed',
    path: '/detailed',
    getParentRoute: () => ApiAnalyticsFormsIdV2Route,
  } as any)
const ApiFormsIdIntegrationsGoogleSheetsConnectRoute =
  ApiFormsIdIntegrationsGoogleSheetsConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => ApiFormsIdIntegrationsGoogleSheetsRoute,
  } as any)
const ApiFormsIdIntegrationsGoogleSheetsCreateRoute =
  ApiFormsIdIntegrationsGoogleSheetsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => ApiFormsIdIntegrationsGoogleSheetsRoute,
  } as any)
const ApiFormsIdIntegrationsGoogleSheetsPickerTokenRoute =
  ApiFormsIdIntegrationsGoogleSheetsPickerTokenRouteImport.update({
    id: '/picker-token',
    path: '/picker-token',
    getParentRoute: () => ApiFormsIdIntegrationsGoogleSheetsRoute,
  } as any)
const ApiFormsIdIntegrationsGoogleSheetsSelectionRoute =
  ApiFormsIdIntegrationsGoogleSheetsSelectionRouteImport.update({
    id: '/selection',
    path: '/selection',
    getParentRoute: () => ApiFormsIdIntegrationsGoogleSheetsRoute,
  } as any)
const ApiFormsIdUploadsFieldsFieldIdConnectRoute =
  ApiFormsIdUploadsFieldsFieldIdConnectRouteImport.update({
    id: '/fields/$fieldId/connect',
    path: '/fields/$fieldId/connect',
    getParentRoute: () => ApiFormsIdUploadsRoute,
  } as any)
const ApiFormsIdUploadsFieldsFieldIdIntegrationRoute =
  ApiFormsIdUploadsFieldsFieldIdIntegrationRouteImport.update({
    id: '/fields/$fieldId/integration',
    path: '/fields/$fieldId/integration',
    getParentRoute: () => ApiFormsIdUploadsRoute,
  } as any)
const ApiFormsIdUploadsFieldsFieldIdPickerTokenRoute =
  ApiFormsIdUploadsFieldsFieldIdPickerTokenRouteImport.update({
    id: '/fields/$fieldId/picker-token',
    path: '/fields/$fieldId/picker-token',
    getParentRoute: () => ApiFormsIdUploadsRoute,
  } as any)
const ApiFormsIdUploadsFieldsFieldIdSelectionRoute =
  ApiFormsIdUploadsFieldsFieldIdSelectionRouteImport.update({
    id: '/fields/$fieldId/selection',
    path: '/fields/$fieldId/selection',
    getParentRoute: () => ApiFormsIdUploadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/api/generatewithai': typeof ApiGeneratewithaiRouteRoute
  '/api/forms': typeof ApiFormsRouteWithChildren
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forms/$id': typeof ApiFormsIdRouteWithChildren
  '/api/forms/import-google-form': typeof ApiFormsImportGoogleFormRouteWithChildren
  '/api/forms/new': typeof ApiFormsNewRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/dashboard/forms/': typeof DashboardFormsIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/forms/$slug/': typeof FormsSlugIndexRoute
  '/api/analytics/forms/$id': typeof ApiAnalyticsFormsIdRouteWithChildren
  '/api/forms/$id/delete': typeof ApiFormsIdDeleteRoute
  '/api/forms/$id/duplicate': typeof ApiFormsIdDuplicateRoute
  '/api/forms/$id/responses': typeof ApiFormsIdResponsesRoute
  '/api/forms/$id/submit': typeof ApiFormsIdSubmitRoute
  '/api/forms/$id/update': typeof ApiFormsIdUpdateRoute
  '/api/forms/$id/uploads': typeof ApiFormsIdUploadsRouteWithChildren
  '/api/forms/$id/viewForm': typeof ApiFormsIdViewFormRoute
  '/api/forms/import-google-form/connect': typeof ApiFormsImportGoogleFormConnectRoute
  '/api/integrations/file-uploads/callback': typeof ApiIntegrationsFileUploadsCallbackRoute
  '/api/integrations/google-forms-import/callback': typeof ApiIntegrationsGoogleFormsImportCallbackRoute
  '/api/integrations/google-sheets/callback': typeof ApiIntegrationsGoogleSheetsCallbackRoute
  '/api/internal/google-sheets/sync': typeof ApiInternalGoogleSheetsSyncRoute
  '/dashboard/forms/$formId/analytics': typeof DashboardFormsFormIdAnalyticsRoute
  '/dashboard/forms/$formId/responses': typeof DashboardFormsFormIdResponsesRoute
  '/dashboard/builder/$slug/': typeof DashboardBuilderSlugIndexRoute
  '/api/analytics/forms/$id/overview': typeof ApiAnalyticsFormsIdOverviewRoute
  '/api/analytics/forms/$id/today': typeof ApiAnalyticsFormsIdTodayRoute
  '/api/analytics/forms/$id/v2': typeof ApiAnalyticsFormsIdV2RouteWithChildren
  '/api/forms/$id/integrations/google-sheets': typeof ApiFormsIdIntegrationsGoogleSheetsRouteWithChildren
  '/api/forms/$id/uploads/$uploadId': typeof ApiFormsIdUploadsUploadIdRoute
  '/api/analytics/forms/$id/v2/detailed': typeof ApiAnalyticsFormsIdV2DetailedRoute
  '/api/forms/$id/integrations/google-sheets/connect': typeof ApiFormsIdIntegrationsGoogleSheetsConnectRoute
  '/api/forms/$id/integrations/google-sheets/create': typeof ApiFormsIdIntegrationsGoogleSheetsCreateRoute
  '/api/forms/$id/integrations/google-sheets/picker-token': typeof ApiFormsIdIntegrationsGoogleSheetsPickerTokenRoute
  '/api/forms/$id/integrations/google-sheets/selection': typeof ApiFormsIdIntegrationsGoogleSheetsSelectionRoute
  '/api/forms/$id/uploads/fields/$fieldId/connect': typeof ApiFormsIdUploadsFieldsFieldIdConnectRoute
  '/api/forms/$id/uploads/fields/$fieldId/integration': typeof ApiFormsIdUploadsFieldsFieldIdIntegrationRoute
  '/api/forms/$id/uploads/fields/$fieldId/picker-token': typeof ApiFormsIdUploadsFieldsFieldIdPickerTokenRoute
  '/api/forms/$id/uploads/fields/$fieldId/selection': typeof ApiFormsIdUploadsFieldsFieldIdSelectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generatewithai': typeof ApiGeneratewithaiRouteRoute
  '/api/forms': typeof ApiFormsRouteWithChildren
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forms/$id': typeof ApiFormsIdRouteWithChildren
  '/api/forms/import-google-form': typeof ApiFormsImportGoogleFormRouteWithChildren
  '/api/forms/new': typeof ApiFormsNewRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/forms': typeof DashboardFormsIndexRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
  '/forms/$slug': typeof FormsSlugIndexRoute
  '/api/analytics/forms/$id': typeof ApiAnalyticsFormsIdRouteWithChildren
  '/api/forms/$id/delete': typeof ApiFormsIdDeleteRoute
  '/api/forms/$id/duplicate': typeof ApiFormsIdDuplicateRoute
  '/api/forms/$id/responses': typeof ApiFormsIdResponsesRoute
  '/api/forms/$id/submit': typeof ApiFormsIdSubmitRoute
  '/api/forms/$id/update': typeof ApiFormsIdUpdateRoute
  '/api/forms/$id/uploads': typeof ApiFormsIdUploadsRouteWithChildren
  '/api/forms/$id/viewForm': typeof ApiFormsIdViewFormRoute
  '/api/forms/import-google-form/connect': typeof ApiFormsImportGoogleFormConnectRoute
  '/api/integrations/file-uploads/callback': typeof ApiIntegrationsFileUploadsCallbackRoute
  '/api/integrations/google-forms-import/callback': typeof ApiIntegrationsGoogleFormsImportCallbackRoute
  '/api/integrations/google-sheets/callback': typeof ApiIntegrationsGoogleSheetsCallbackRoute
  '/api/internal/google-sheets/sync': typeof ApiInternalGoogleSheetsSyncRoute
  '/dashboard/forms/$formId/analytics': typeof DashboardFormsFormIdAnalyticsRoute
  '/dashboard/forms/$formId/responses': typeof DashboardFormsFormIdResponsesRoute
  '/dashboard/builder/$slug': typeof DashboardBuilderSlugIndexRoute
  '/api/analytics/forms/$id/overview': typeof ApiAnalyticsFormsIdOverviewRoute
  '/api/analytics/forms/$id/today': typeof ApiAnalyticsFormsIdTodayRoute
  '/api/analytics/forms/$id/v2': typeof ApiAnalyticsFormsIdV2RouteWithChildren
  '/api/forms/$id/integrations/google-sheets': typeof ApiFormsIdIntegrationsGoogleSheetsRouteWithChildren
  '/api/forms/$id/uploads/$uploadId': typeof ApiFormsIdUploadsUploadIdRoute
  '/api/analytics/forms/$id/v2/detailed': typeof ApiAnalyticsFormsIdV2DetailedRoute
  '/api/forms/$id/integrations/google-sheets/connect': typeof ApiFormsIdIntegrationsGoogleSheetsConnectRoute
  '/api/forms/$id/integrations/google-sheets/create': typeof ApiFormsIdIntegrationsGoogleSheetsCreateRoute
  '/api/forms/$id/integrations/google-sheets/picker-token': typeof ApiFormsIdIntegrationsGoogleSheetsPickerTokenRoute
  '/api/forms/$id/integrations/google-sheets/selection': typeof ApiFormsIdIntegrationsGoogleSheetsSelectionRoute
  '/api/forms/$id/uploads/fields/$fieldId/connect': typeof ApiFormsIdUploadsFieldsFieldIdConnectRoute
  '/api/forms/$id/uploads/fields/$fieldId/integration': typeof ApiFormsIdUploadsFieldsFieldIdIntegrationRoute
  '/api/forms/$id/uploads/fields/$fieldId/picker-token': typeof ApiFormsIdUploadsFieldsFieldIdPickerTokenRoute
  '/api/forms/$id/uploads/fields/$fieldId/selection': typeof ApiFormsIdUploadsFieldsFieldIdSelectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/api/generatewithai': typeof ApiGeneratewithaiRouteRoute
  '/api/forms': typeof ApiFormsRouteWithChildren
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forms/$id': typeof ApiFormsIdRouteWithChildren
  '/api/forms/import-google-form': typeof ApiFormsImportGoogleFormRouteWithChildren
  '/api/forms/new': typeof ApiFormsNewRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/dashboard/forms/': typeof DashboardFormsIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/forms/$slug/': typeof FormsSlugIndexRoute
  '/api/analytics/forms/$id': typeof ApiAnalyticsFormsIdRouteWithChildren
  '/api/forms/$id/delete': typeof ApiFormsIdDeleteRoute
  '/api/forms/$id/duplicate': typeof ApiFormsIdDuplicateRoute
  '/api/forms/$id/responses': typeof ApiFormsIdResponsesRoute
  '/api/forms/$id/submit': typeof ApiFormsIdSubmitRoute
  '/api/forms/$id/update': typeof ApiFormsIdUpdateRoute
  '/api/forms/$id/uploads': typeof ApiFormsIdUploadsRouteWithChildren
  '/api/forms/$id/viewForm': typeof ApiFormsIdViewFormRoute
  '/api/forms/import-google-form/connect': typeof ApiFormsImportGoogleFormConnectRoute
  '/api/integrations/file-uploads/callback': typeof ApiIntegrationsFileUploadsCallbackRoute
  '/api/integrations/google-forms-import/callback': typeof ApiIntegrationsGoogleFormsImportCallbackRoute
  '/api/integrations/google-sheets/callback': typeof ApiIntegrationsGoogleSheetsCallbackRoute
  '/api/internal/google-sheets/sync': typeof ApiInternalGoogleSheetsSyncRoute
  '/dashboard/forms/$formId/analytics': typeof DashboardFormsFormIdAnalyticsRoute
  '/dashboard/forms/$formId/responses': typeof DashboardFormsFormIdResponsesRoute
  '/dashboard/builder/$slug/': typeof DashboardBuilderSlugIndexRoute
  '/api/analytics/forms/$id/overview': typeof ApiAnalyticsFormsIdOverviewRoute
  '/api/analytics/forms/$id/today': typeof ApiAnalyticsFormsIdTodayRoute
  '/api/analytics/forms/$id/v2': typeof ApiAnalyticsFormsIdV2RouteWithChildren
  '/api/forms/$id/integrations/google-sheets': typeof ApiFormsIdIntegrationsGoogleSheetsRouteWithChildren
  '/api/forms/$id/uploads/$uploadId': typeof ApiFormsIdUploadsUploadIdRoute
  '/api/analytics/forms/$id/v2/detailed': typeof ApiAnalyticsFormsIdV2DetailedRoute
  '/api/forms/$id/integrations/google-sheets/connect': typeof ApiFormsIdIntegrationsGoogleSheetsConnectRoute
  '/api/forms/$id/integrations/google-sheets/create': typeof ApiFormsIdIntegrationsGoogleSheetsCreateRoute
  '/api/forms/$id/integrations/google-sheets/picker-token': typeof ApiFormsIdIntegrationsGoogleSheetsPickerTokenRoute
  '/api/forms/$id/integrations/google-sheets/selection': typeof ApiFormsIdIntegrationsGoogleSheetsSelectionRoute
  '/api/forms/$id/uploads/fields/$fieldId/connect': typeof ApiFormsIdUploadsFieldsFieldIdConnectRoute
  '/api/forms/$id/uploads/fields/$fieldId/integration': typeof ApiFormsIdUploadsFieldsFieldIdIntegrationRoute
  '/api/forms/$id/uploads/fields/$fieldId/picker-token': typeof ApiFormsIdUploadsFieldsFieldIdPickerTokenRoute
  '/api/forms/$id/uploads/fields/$fieldId/selection': typeof ApiFormsIdUploadsFieldsFieldIdSelectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/generatewithai'
    | '/api/forms'
    | '/api/healthcheck'
    | '/api/templates'
    | '/auth/'
    | '/dashboard/'
    | '/templates/'
    | '/api/analytics/overview'
    | '/api/auth/$'
    | '/api/forms/$id'
    | '/api/forms/import-google-form'
    | '/api/forms/new'
    | '/auth/login/'
    | '/auth/signup/'
    | '/dashboard/forms/'
    | '/dashboard/templates/'
    | '/forms/$slug/'
    | '/api/analytics/forms/$id'
    | '/api/forms/$id/delete'
    | '/api/forms/$id/duplicate'
    | '/api/forms/$id/responses'
    | '/api/forms/$id/submit'
    | '/api/forms/$id/update'
    | '/api/forms/$id/uploads'
    | '/api/forms/$id/viewForm'
    | '/api/forms/import-google-form/connect'
    | '/api/integrations/file-uploads/callback'
    | '/api/integrations/google-forms-import/callback'
    | '/api/integrations/google-sheets/callback'
    | '/api/internal/google-sheets/sync'
    | '/dashboard/forms/$formId/analytics'
    | '/dashboard/forms/$formId/responses'
    | '/dashboard/builder/$slug/'
    | '/api/analytics/forms/$id/overview'
    | '/api/analytics/forms/$id/today'
    | '/api/analytics/forms/$id/v2'
    | '/api/forms/$id/integrations/google-sheets'
    | '/api/forms/$id/uploads/$uploadId'
    | '/api/analytics/forms/$id/v2/detailed'
    | '/api/forms/$id/integrations/google-sheets/connect'
    | '/api/forms/$id/integrations/google-sheets/create'
    | '/api/forms/$id/integrations/google-sheets/picker-token'
    | '/api/forms/$id/integrations/google-sheets/selection'
    | '/api/forms/$id/uploads/fields/$fieldId/connect'
    | '/api/forms/$id/uploads/fields/$fieldId/integration'
    | '/api/forms/$id/uploads/fields/$fieldId/picker-token'
    | '/api/forms/$id/uploads/fields/$fieldId/selection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/generatewithai'
    | '/api/forms'
    | '/api/healthcheck'
    | '/api/templates'
    | '/auth'
    | '/dashboard'
    | '/templates'
    | '/api/analytics/overview'
    | '/api/auth/$'
    | '/api/forms/$id'
    | '/api/forms/import-google-form'
    | '/api/forms/new'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/forms'
    | '/dashboard/templates'
    | '/forms/$slug'
    | '/api/analytics/forms/$id'
    | '/api/forms/$id/delete'
    | '/api/forms/$id/duplicate'
    | '/api/forms/$id/responses'
    | '/api/forms/$id/submit'
    | '/api/forms/$id/update'
    | '/api/forms/$id/uploads'
    | '/api/forms/$id/viewForm'
    | '/api/forms/import-google-form/connect'
    | '/api/integrations/file-uploads/callback'
    | '/api/integrations/google-forms-import/callback'
    | '/api/integrations/google-sheets/callback'
    | '/api/internal/google-sheets/sync'
    | '/dashboard/forms/$formId/analytics'
    | '/dashboard/forms/$formId/responses'
    | '/dashboard/builder/$slug'
    | '/api/analytics/forms/$id/overview'
    | '/api/analytics/forms/$id/today'
    | '/api/analytics/forms/$id/v2'
    | '/api/forms/$id/integrations/google-sheets'
    | '/api/forms/$id/uploads/$uploadId'
    | '/api/analytics/forms/$id/v2/detailed'
    | '/api/forms/$id/integrations/google-sheets/connect'
    | '/api/forms/$id/integrations/google-sheets/create'
    | '/api/forms/$id/integrations/google-sheets/picker-token'
    | '/api/forms/$id/integrations/google-sheets/selection'
    | '/api/forms/$id/uploads/fields/$fieldId/connect'
    | '/api/forms/$id/uploads/fields/$fieldId/integration'
    | '/api/forms/$id/uploads/fields/$fieldId/picker-token'
    | '/api/forms/$id/uploads/fields/$fieldId/selection'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/generatewithai'
    | '/api/forms'
    | '/api/healthcheck'
    | '/api/templates'
    | '/auth/'
    | '/dashboard/'
    | '/templates/'
    | '/api/analytics/overview'
    | '/api/auth/$'
    | '/api/forms/$id'
    | '/api/forms/import-google-form'
    | '/api/forms/new'
    | '/auth/login/'
    | '/auth/signup/'
    | '/dashboard/forms/'
    | '/dashboard/templates/'
    | '/forms/$slug/'
    | '/api/analytics/forms/$id'
    | '/api/forms/$id/delete'
    | '/api/forms/$id/duplicate'
    | '/api/forms/$id/responses'
    | '/api/forms/$id/submit'
    | '/api/forms/$id/update'
    | '/api/forms/$id/uploads'
    | '/api/forms/$id/viewForm'
    | '/api/forms/import-google-form/connect'
    | '/api/integrations/file-uploads/callback'
    | '/api/integrations/google-forms-import/callback'
    | '/api/integrations/google-sheets/callback'
    | '/api/internal/google-sheets/sync'
    | '/dashboard/forms/$formId/analytics'
    | '/dashboard/forms/$formId/responses'
    | '/dashboard/builder/$slug/'
    | '/api/analytics/forms/$id/overview'
    | '/api/analytics/forms/$id/today'
    | '/api/analytics/forms/$id/v2'
    | '/api/forms/$id/integrations/google-sheets'
    | '/api/forms/$id/uploads/$uploadId'
    | '/api/analytics/forms/$id/v2/detailed'
    | '/api/forms/$id/integrations/google-sheets/connect'
    | '/api/forms/$id/integrations/google-sheets/create'
    | '/api/forms/$id/integrations/google-sheets/picker-token'
    | '/api/forms/$id/integrations/google-sheets/selection'
    | '/api/forms/$id/uploads/fields/$fieldId/connect'
    | '/api/forms/$id/uploads/fields/$fieldId/integration'
    | '/api/forms/$id/uploads/fields/$fieldId/picker-token'
    | '/api/forms/$id/uploads/fields/$fieldId/selection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiGeneratewithaiRouteRoute: typeof ApiGeneratewithaiRouteRoute
  ApiFormsRoute: typeof ApiFormsRouteWithChildren
  ApiHealthcheckRoute: typeof ApiHealthcheckRoute
  ApiTemplatesRoute: typeof ApiTemplatesRoute
  AuthIndexRoute: typeof AuthIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ApiAnalyticsOverviewRoute: typeof ApiAnalyticsOverviewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  FormsSlugIndexRoute: typeof FormsSlugIndexRoute
  ApiAnalyticsFormsIdRoute: typeof ApiAnalyticsFormsIdRouteWithChildren
  ApiIntegrationsFileUploadsCallbackRoute: typeof ApiIntegrationsFileUploadsCallbackRoute
  ApiIntegrationsGoogleFormsImportCallbackRoute: typeof ApiIntegrationsGoogleFormsImportCallbackRoute
  ApiIntegrationsGoogleSheetsCallbackRoute: typeof ApiIntegrationsGoogleSheetsCallbackRoute
  ApiInternalGoogleSheetsSyncRoute: typeof ApiInternalGoogleSheetsSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms': {
      id: '/api/forms'
      path: '/api/forms'
      fullPath: '/api/forms'
      preLoaderRoute: typeof ApiFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generatewithai': {
      id: '/api/generatewithai'
      path: '/api/generatewithai'
      fullPath: '/api/generatewithai'
      preLoaderRoute: typeof ApiGeneratewithaiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthcheck': {
      id: '/api/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates': {
      id: '/api/templates'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/overview': {
      id: '/api/analytics/overview'
      path: '/api/analytics/overview'
      fullPath: '/api/analytics/overview'
      preLoaderRoute: typeof ApiAnalyticsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/$id': {
      id: '/api/forms/$id'
      path: '/$id'
      fullPath: '/api/forms/$id'
      preLoaderRoute: typeof ApiFormsIdRouteImport
      parentRoute: typeof ApiFormsRoute
    }
    '/api/forms/import-google-form': {
      id: '/api/forms/import-google-form'
      path: '/import-google-form'
      fullPath: '/api/forms/import-google-form'
      preLoaderRoute: typeof ApiFormsImportGoogleFormRouteImport
      parentRoute: typeof ApiFormsRoute
    }
    '/api/forms/new': {
      id: '/api/forms/new'
      path: '/new'
      fullPath: '/api/forms/new'
      preLoaderRoute: typeof ApiFormsNewRouteImport
      parentRoute: typeof ApiFormsRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/forms/': {
      id: '/dashboard/forms/'
      path: '/forms'
      fullPath: '/dashboard/forms/'
      preLoaderRoute: typeof DashboardFormsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/templates/': {
      id: '/dashboard/templates/'
      path: '/templates'
      fullPath: '/dashboard/templates/'
      preLoaderRoute: typeof DashboardTemplatesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/forms/$slug/': {
      id: '/forms/$slug/'
      path: '/forms/$slug'
      fullPath: '/forms/$slug/'
      preLoaderRoute: typeof FormsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/forms/$id': {
      id: '/api/analytics/forms/$id'
      path: '/api/analytics/forms/$id'
      fullPath: '/api/analytics/forms/$id'
      preLoaderRoute: typeof ApiAnalyticsFormsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/$id/delete': {
      id: '/api/forms/$id/delete'
      path: '/delete'
      fullPath: '/api/forms/$id/delete'
      preLoaderRoute: typeof ApiFormsIdDeleteRouteImport
      parentRoute: typeof ApiFormsIdRoute
    }
    '/api/forms/$id/duplicate': {
      id: '/api/forms/$id/duplicate'
      path: '/duplicate'
      fullPath: '/api/forms/$id/duplicate'
      preLoaderRoute: typeof ApiFormsIdDuplicateRouteImport
      parentRoute: typeof ApiFormsIdRoute
    }
    '/api/forms/$id/responses': {
      id: '/api/forms/$id/responses'
      path: '/responses'
      fullPath: '/api/forms/$id/responses'
      preLoaderRoute: typeof ApiFormsIdResponsesRouteImport
      parentRoute: typeof ApiFormsIdRoute
    }
    '/api/forms/$id/submit': {
      id: '/api/forms/$id/submit'
      path: '/submit'
      fullPath: '/api/forms/$id/submit'
      preLoaderRoute: typeof ApiFormsIdSubmitRouteImport
      parentRoute: typeof ApiFormsIdRoute
    }
    '/api/forms/$id/update': {
      id: '/api/forms/$id/update'
      path: '/update'
      fullPath: '/api/forms/$id/update'
      preLoaderRoute: typeof ApiFormsIdUpdateRouteImport
      parentRoute: typeof ApiFormsIdRoute
    }
    '/api/forms/$id/uploads': {
      id: '/api/forms/$id/uploads'
      path: '/uploads'
      fullPath: '/api/forms/$id/uploads'
      preLoaderRoute: typeof ApiFormsIdUploadsRouteImport
      parentRoute: typeof ApiFormsIdRoute
    }
    '/api/forms/$id/viewForm': {
      id: '/api/forms/$id/viewForm'
      path: '/viewForm'
      fullPath: '/api/forms/$id/viewForm'
      preLoaderRoute: typeof ApiFormsIdViewFormRouteImport
      parentRoute: typeof ApiFormsIdRoute
    }
    '/api/forms/import-google-form/connect': {
      id: '/api/forms/import-google-form/connect'
      path: '/connect'
      fullPath: '/api/forms/import-google-form/connect'
      preLoaderRoute: typeof ApiFormsImportGoogleFormConnectRouteImport
      parentRoute: typeof ApiFormsImportGoogleFormRoute
    }
    '/api/integrations/file-uploads/callback': {
      id: '/api/integrations/file-uploads/callback'
      path: '/api/integrations/file-uploads/callback'
      fullPath: '/api/integrations/file-uploads/callback'
      preLoaderRoute: typeof ApiIntegrationsFileUploadsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-forms-import/callback': {
      id: '/api/integrations/google-forms-import/callback'
      path: '/api/integrations/google-forms-import/callback'
      fullPath: '/api/integrations/google-forms-import/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleFormsImportCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/callback': {
      id: '/api/integrations/google-sheets/callback'
      path: '/api/integrations/google-sheets/callback'
      fullPath: '/api/integrations/google-sheets/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/google-sheets/sync': {
      id: '/api/internal/google-sheets/sync'
      path: '/api/internal/google-sheets/sync'
      fullPath: '/api/internal/google-sheets/sync'
      preLoaderRoute: typeof ApiInternalGoogleSheetsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/builder/$slug/': {
      id: '/dashboard/builder/$slug/'
      path: '/builder/$slug'
      fullPath: '/dashboard/builder/$slug/'
      preLoaderRoute: typeof DashboardBuilderSlugIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/forms/$formId/analytics': {
      id: '/dashboard/forms/$formId/analytics'
      path: '/forms/$formId/analytics'
      fullPath: '/dashboard/forms/$formId/analytics'
      preLoaderRoute: typeof DashboardFormsFormIdAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/forms/$formId/responses': {
      id: '/dashboard/forms/$formId/responses'
      path: '/forms/$formId/responses'
      fullPath: '/dashboard/forms/$formId/responses'
      preLoaderRoute: typeof DashboardFormsFormIdResponsesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/analytics/forms/$id/overview': {
      id: '/api/analytics/forms/$id/overview'
      path: '/overview'
      fullPath: '/api/analytics/forms/$id/overview'
      preLoaderRoute: typeof ApiAnalyticsFormsIdOverviewRouteImport
      parentRoute: typeof ApiAnalyticsFormsIdRoute
    }
    '/api/analytics/forms/$id/today': {
      id: '/api/analytics/forms/$id/today'
      path: '/today'
      fullPath: '/api/analytics/forms/$id/today'
      preLoaderRoute: typeof ApiAnalyticsFormsIdTodayRouteImport
      parentRoute: typeof ApiAnalyticsFormsIdRoute
    }
    '/api/analytics/forms/$id/v2': {
      id: '/api/analytics/forms/$id/v2'
      path: '/v2'
      fullPath: '/api/analytics/forms/$id/v2'
      preLoaderRoute: typeof ApiAnalyticsFormsIdV2RouteImport
      parentRoute: typeof ApiAnalyticsFormsIdRoute
    }
    '/api/forms/$id/integrations/google-sheets': {
      id: '/api/forms/$id/integrations/google-sheets'
      path: '/integrations/google-sheets'
      fullPath: '/api/forms/$id/integrations/google-sheets'
      preLoaderRoute: typeof ApiFormsIdIntegrationsGoogleSheetsRouteImport
      parentRoute: typeof ApiFormsIdRoute
    }
    '/api/forms/$id/uploads/$uploadId': {
      id: '/api/forms/$id/uploads/$uploadId'
      path: '/$uploadId'
      fullPath: '/api/forms/$id/uploads/$uploadId'
      preLoaderRoute: typeof ApiFormsIdUploadsUploadIdRouteImport
      parentRoute: typeof ApiFormsIdUploadsRoute
    }
    '/api/analytics/forms/$id/v2/detailed': {
      id: '/api/analytics/forms/$id/v2/detailed'
      path: '/detailed'
      fullPath: '/api/analytics/forms/$id/v2/detailed'
      preLoaderRoute: typeof ApiAnalyticsFormsIdV2DetailedRouteImport
      parentRoute: typeof ApiAnalyticsFormsIdV2Route
    }
    '/api/forms/$id/integrations/google-sheets/connect': {
      id: '/api/forms/$id/integrations/google-sheets/connect'
      path: '/connect'
      fullPath: '/api/forms/$id/integrations/google-sheets/connect'
      preLoaderRoute: typeof ApiFormsIdIntegrationsGoogleSheetsConnectRouteImport
      parentRoute: typeof ApiFormsIdIntegrationsGoogleSheetsRoute
    }
    '/api/forms/$id/integrations/google-sheets/create': {
      id: '/api/forms/$id/integrations/google-sheets/create'
      path: '/create'
      fullPath: '/api/forms/$id/integrations/google-sheets/create'
      preLoaderRoute: typeof ApiFormsIdIntegrationsGoogleSheetsCreateRouteImport
      parentRoute: typeof ApiFormsIdIntegrationsGoogleSheetsRoute
    }
    '/api/forms/$id/integrations/google-sheets/picker-token': {
      id: '/api/forms/$id/integrations/google-sheets/picker-token'
      path: '/picker-token'
      fullPath: '/api/forms/$id/integrations/google-sheets/picker-token'
      preLoaderRoute: typeof ApiFormsIdIntegrationsGoogleSheetsPickerTokenRouteImport
      parentRoute: typeof ApiFormsIdIntegrationsGoogleSheetsRoute
    }
    '/api/forms/$id/integrations/google-sheets/selection': {
      id: '/api/forms/$id/integrations/google-sheets/selection'
      path: '/selection'
      fullPath: '/api/forms/$id/integrations/google-sheets/selection'
      preLoaderRoute: typeof ApiFormsIdIntegrationsGoogleSheetsSelectionRouteImport
      parentRoute: typeof ApiFormsIdIntegrationsGoogleSheetsRoute
    }
    '/api/forms/$id/uploads/fields/$fieldId/connect': {
      id: '/api/forms/$id/uploads/fields/$fieldId/connect'
      path: '/fields/$fieldId/connect'
      fullPath: '/api/forms/$id/uploads/fields/$fieldId/connect'
      preLoaderRoute: typeof ApiFormsIdUploadsFieldsFieldIdConnectRouteImport
      parentRoute: typeof ApiFormsIdUploadsRoute
    }
    '/api/forms/$id/uploads/fields/$fieldId/integration': {
      id: '/api/forms/$id/uploads/fields/$fieldId/integration'
      path: '/fields/$fieldId/integration'
      fullPath: '/api/forms/$id/uploads/fields/$fieldId/integration'
      preLoaderRoute: typeof ApiFormsIdUploadsFieldsFieldIdIntegrationRouteImport
      parentRoute: typeof ApiFormsIdUploadsRoute
    }
    '/api/forms/$id/uploads/fields/$fieldId/picker-token': {
      id: '/api/forms/$id/uploads/fields/$fieldId/picker-token'
      path: '/fields/$fieldId/picker-token'
      fullPath: '/api/forms/$id/uploads/fields/$fieldId/picker-token'
      preLoaderRoute: typeof ApiFormsIdUploadsFieldsFieldIdPickerTokenRouteImport
      parentRoute: typeof ApiFormsIdUploadsRoute
    }
    '/api/forms/$id/uploads/fields/$fieldId/selection': {
      id: '/api/forms/$id/uploads/fields/$fieldId/selection'
      path: '/fields/$fieldId/selection'
      fullPath: '/api/forms/$id/uploads/fields/$fieldId/selection'
      preLoaderRoute: typeof ApiFormsIdUploadsFieldsFieldIdSelectionRouteImport
      parentRoute: typeof ApiFormsIdUploadsRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFormsIndexRoute: typeof DashboardFormsIndexRoute
  DashboardTemplatesIndexRoute: typeof DashboardTemplatesIndexRoute
  DashboardFormsFormIdAnalyticsRoute: typeof DashboardFormsFormIdAnalyticsRoute
  DashboardFormsFormIdResponsesRoute: typeof DashboardFormsFormIdResponsesRoute
  DashboardBuilderSlugIndexRoute: typeof DashboardBuilderSlugIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFormsIndexRoute: DashboardFormsIndexRoute,
  DashboardTemplatesIndexRoute: DashboardTemplatesIndexRoute,
  DashboardFormsFormIdAnalyticsRoute: DashboardFormsFormIdAnalyticsRoute,
  DashboardFormsFormIdResponsesRoute: DashboardFormsFormIdResponsesRoute,
  DashboardBuilderSlugIndexRoute: DashboardBuilderSlugIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ApiFormsIdUploadsRouteChildren {
  ApiFormsIdUploadsUploadIdRoute: typeof ApiFormsIdUploadsUploadIdRoute
  ApiFormsIdUploadsFieldsFieldIdConnectRoute: typeof ApiFormsIdUploadsFieldsFieldIdConnectRoute
  ApiFormsIdUploadsFieldsFieldIdIntegrationRoute: typeof ApiFormsIdUploadsFieldsFieldIdIntegrationRoute
  ApiFormsIdUploadsFieldsFieldIdPickerTokenRoute: typeof ApiFormsIdUploadsFieldsFieldIdPickerTokenRoute
  ApiFormsIdUploadsFieldsFieldIdSelectionRoute: typeof ApiFormsIdUploadsFieldsFieldIdSelectionRoute
}

const ApiFormsIdUploadsRouteChildren: ApiFormsIdUploadsRouteChildren = {
  ApiFormsIdUploadsUploadIdRoute: ApiFormsIdUploadsUploadIdRoute,
  ApiFormsIdUploadsFieldsFieldIdConnectRoute:
    ApiFormsIdUploadsFieldsFieldIdConnectRoute,
  ApiFormsIdUploadsFieldsFieldIdIntegrationRoute:
    ApiFormsIdUploadsFieldsFieldIdIntegrationRoute,
  ApiFormsIdUploadsFieldsFieldIdPickerTokenRoute:
    ApiFormsIdUploadsFieldsFieldIdPickerTokenRoute,
  ApiFormsIdUploadsFieldsFieldIdSelectionRoute:
    ApiFormsIdUploadsFieldsFieldIdSelectionRoute,
}

const ApiFormsIdUploadsRouteWithChildren =
  ApiFormsIdUploadsRoute._addFileChildren(ApiFormsIdUploadsRouteChildren)

interface ApiFormsIdIntegrationsGoogleSheetsRouteChildren {
  ApiFormsIdIntegrationsGoogleSheetsConnectRoute: typeof ApiFormsIdIntegrationsGoogleSheetsConnectRoute
  ApiFormsIdIntegrationsGoogleSheetsCreateRoute: typeof ApiFormsIdIntegrationsGoogleSheetsCreateRoute
  ApiFormsIdIntegrationsGoogleSheetsPickerTokenRoute: typeof ApiFormsIdIntegrationsGoogleSheetsPickerTokenRoute
  ApiFormsIdIntegrationsGoogleSheetsSelectionRoute: typeof ApiFormsIdIntegrationsGoogleSheetsSelectionRoute
}

const ApiFormsIdIntegrationsGoogleSheetsRouteChildren: ApiFormsIdIntegrationsGoogleSheetsRouteChildren =
  {
    ApiFormsIdIntegrationsGoogleSheetsConnectRoute:
      ApiFormsIdIntegrationsGoogleSheetsConnectRoute,
    ApiFormsIdIntegrationsGoogleSheetsCreateRoute:
      ApiFormsIdIntegrationsGoogleSheetsCreateRoute,
    ApiFormsIdIntegrationsGoogleSheetsPickerTokenRoute:
      ApiFormsIdIntegrationsGoogleSheetsPickerTokenRoute,
    ApiFormsIdIntegrationsGoogleSheetsSelectionRoute:
      ApiFormsIdIntegrationsGoogleSheetsSelectionRoute,
  }

const ApiFormsIdIntegrationsGoogleSheetsRouteWithChildren =
  ApiFormsIdIntegrationsGoogleSheetsRoute._addFileChildren(
    ApiFormsIdIntegrationsGoogleSheetsRouteChildren,
  )

interface ApiFormsIdRouteChildren {
  ApiFormsIdDeleteRoute: typeof ApiFormsIdDeleteRoute
  ApiFormsIdDuplicateRoute: typeof ApiFormsIdDuplicateRoute
  ApiFormsIdResponsesRoute: typeof ApiFormsIdResponsesRoute
  ApiFormsIdSubmitRoute: typeof ApiFormsIdSubmitRoute
  ApiFormsIdUpdateRoute: typeof ApiFormsIdUpdateRoute
  ApiFormsIdUploadsRoute: typeof ApiFormsIdUploadsRouteWithChildren
  ApiFormsIdViewFormRoute: typeof ApiFormsIdViewFormRoute
  ApiFormsIdIntegrationsGoogleSheetsRoute: typeof ApiFormsIdIntegrationsGoogleSheetsRouteWithChildren
}

const ApiFormsIdRouteChildren: ApiFormsIdRouteChildren = {
  ApiFormsIdDeleteRoute: ApiFormsIdDeleteRoute,
  ApiFormsIdDuplicateRoute: ApiFormsIdDuplicateRoute,
  ApiFormsIdResponsesRoute: ApiFormsIdResponsesRoute,
  ApiFormsIdSubmitRoute: ApiFormsIdSubmitRoute,
  ApiFormsIdUpdateRoute: ApiFormsIdUpdateRoute,
  ApiFormsIdUploadsRoute: ApiFormsIdUploadsRouteWithChildren,
  ApiFormsIdViewFormRoute: ApiFormsIdViewFormRoute,
  ApiFormsIdIntegrationsGoogleSheetsRoute:
    ApiFormsIdIntegrationsGoogleSheetsRouteWithChildren,
}

const ApiFormsIdRouteWithChildren = ApiFormsIdRoute._addFileChildren(
  ApiFormsIdRouteChildren,
)

interface ApiFormsImportGoogleFormRouteChildren {
  ApiFormsImportGoogleFormConnectRoute: typeof ApiFormsImportGoogleFormConnectRoute
}

const ApiFormsImportGoogleFormRouteChildren: ApiFormsImportGoogleFormRouteChildren =
  {
    ApiFormsImportGoogleFormConnectRoute: ApiFormsImportGoogleFormConnectRoute,
  }

const ApiFormsImportGoogleFormRouteWithChildren =
  ApiFormsImportGoogleFormRoute._addFileChildren(
    ApiFormsImportGoogleFormRouteChildren,
  )

interface ApiFormsRouteChildren {
  ApiFormsIdRoute: typeof ApiFormsIdRouteWithChildren
  ApiFormsImportGoogleFormRoute: typeof ApiFormsImportGoogleFormRouteWithChildren
  ApiFormsNewRoute: typeof ApiFormsNewRoute
}

const ApiFormsRouteChildren: ApiFormsRouteChildren = {
  ApiFormsIdRoute: ApiFormsIdRouteWithChildren,
  ApiFormsImportGoogleFormRoute: ApiFormsImportGoogleFormRouteWithChildren,
  ApiFormsNewRoute: ApiFormsNewRoute,
}

const ApiFormsRouteWithChildren = ApiFormsRoute._addFileChildren(
  ApiFormsRouteChildren,
)

interface ApiAnalyticsFormsIdV2RouteChildren {
  ApiAnalyticsFormsIdV2DetailedRoute: typeof ApiAnalyticsFormsIdV2DetailedRoute
}

const ApiAnalyticsFormsIdV2RouteChildren: ApiAnalyticsFormsIdV2RouteChildren = {
  ApiAnalyticsFormsIdV2DetailedRoute: ApiAnalyticsFormsIdV2DetailedRoute,
}

const ApiAnalyticsFormsIdV2RouteWithChildren =
  ApiAnalyticsFormsIdV2Route._addFileChildren(
    ApiAnalyticsFormsIdV2RouteChildren,
  )

interface ApiAnalyticsFormsIdRouteChildren {
  ApiAnalyticsFormsIdOverviewRoute: typeof ApiAnalyticsFormsIdOverviewRoute
  ApiAnalyticsFormsIdTodayRoute: typeof ApiAnalyticsFormsIdTodayRoute
  ApiAnalyticsFormsIdV2Route: typeof ApiAnalyticsFormsIdV2RouteWithChildren
}

const ApiAnalyticsFormsIdRouteChildren: ApiAnalyticsFormsIdRouteChildren = {
  ApiAnalyticsFormsIdOverviewRoute: ApiAnalyticsFormsIdOverviewRoute,
  ApiAnalyticsFormsIdTodayRoute: ApiAnalyticsFormsIdTodayRoute,
  ApiAnalyticsFormsIdV2Route: ApiAnalyticsFormsIdV2RouteWithChildren,
}

const ApiAnalyticsFormsIdRouteWithChildren =
  ApiAnalyticsFormsIdRoute._addFileChildren(ApiAnalyticsFormsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiGeneratewithaiRouteRoute: ApiGeneratewithaiRouteRoute,
  ApiFormsRoute: ApiFormsRouteWithChildren,
  ApiHealthcheckRoute: ApiHealthcheckRoute,
  ApiTemplatesRoute: ApiTemplatesRoute,
  AuthIndexRoute: AuthIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ApiAnalyticsOverviewRoute: ApiAnalyticsOverviewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  FormsSlugIndexRoute: FormsSlugIndexRoute,
  ApiAnalyticsFormsIdRoute: ApiAnalyticsFormsIdRouteWithChildren,
  ApiIntegrationsFileUploadsCallbackRoute:
    ApiIntegrationsFileUploadsCallbackRoute,
  ApiIntegrationsGoogleFormsImportCallbackRoute:
    ApiIntegrationsGoogleFormsImportCallbackRoute,
  ApiIntegrationsGoogleSheetsCallbackRoute:
    ApiIntegrationsGoogleSheetsCallbackRoute,
  ApiInternalGoogleSheetsSyncRoute: ApiInternalGoogleSheetsSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
